<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();?>
<table>
	<tr>
		<td>Имя</td>
		<td><?$arResult['name']?></td>
	</tr>
	<tr>
		<td>Телефон</td>
		<td><?$arResult['phone']?></td>
	</tr>
	<tr>
		<td>E-mail</td>
		<td><?$arResult['mail']?></td>
	</tr>
	<tr>
		<td>Комментарий</td>
		<td><?$arResult['comment']?></td>
	</tr>
</table>